{{- if and .Values.postgresql.enabled .Values.postgresql.auth.password (not .Values.postgresql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "colanode.fullname" . }}-postgresql
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }} 