apiVersion: v1
kind: Service
metadata:
  name: {{ include "colanode.fullname" . }}
  labels: {{- include "colanode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.colanode.service.type }}
  ports:
    - port: {{ .Values.colanode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "colanode.selectorLabels" . | nindent 4 }}