{{- if .Values.colanode.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "colanode.serviceAccountName" . }}
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
  {{- with .Values.colanode.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.colanode.serviceAccount.automount }}
{{- end }}
