{{- if and .Values.valkey.enabled .Values.valkey.auth.enabled .Values.valkey.auth.password (not .Values.valkey.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "colanode.fullname" . }}-valkey
  labels:
    {{- include "colanode.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.valkey.auth.secretKeys.redisPasswordKey }}: {{ .Values.valkey.auth.password | b64enc | quote }}
{{- end }} 