apiVersion: v2
name: colanode
description: A Helm chart for Colanode - open-source & local-first collaboration workspace
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "16.7.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: valkey
    version: "3.0.4"
    repository: "https://charts.bitnami.com/bitnami"
    alias: redis
    condition: redis.enabled
  - name: minio
    version: "16.0.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
