apiVersion: v1
entries:
  colanode:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-05-23T10:26:52.71703+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.7.4
    - alias: redis
      condition: redis.enabled
      name: valkey
      repository: https://charts.bitnami.com/bitnami
      version: 3.0.4
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 16.0.10
    description: A Helm chart for Colanode - open-source & local-first collaboration
      workspace
    digest: 22f6abcd471b69673089720619d1ae9e7b98218e353726dd154a38db0212aaa6
    name: colanode
    type: application
    urls:
    - colanode-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-05-23T10:26:52.70683+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.7.4
    - alias: redis
      condition: redis.enabled
      name: valkey
      repository: https://charts.bitnami.com/bitnami
      version: 3.0.4
    - condition: minio.enabled
      name: minio
      repository: https://charts.bitnami.com/bitnami
      version: 16.0.10
    description: A Helm chart for Colanode - open-source & local-first collaboration
      workspace
    digest: 625ec3a019f15b7100d2522acc03100f819e416ef993c0de4bed5615a0d45c6b
    name: colanode
    type: application
    urls:
    - colanode-0.1.0.tgz
    version: 0.1.0
  minio:
  - annotations:
      category: Infrastructure
      images: |
        - name: minio
          image: docker.io/bitnami/minio:2025.4.22-debian-12-r1
        - name: minio-client
          image: docker.io/bitnami/minio-client:2025.4.16-debian-12-r1
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r43
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 2025.4.22
    created: "2025-05-23T10:26:52.718995+02:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
      storage service, mainly used for storing unstructured data (such as photos,
      videos, log files, etc.).
    digest: e21c18f91417eecee69715fd119a577cacf0d5ed0692ee21d1c514ec9e318686
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: minio
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/minio
    urls:
    - charts/minio-16.0.10.tgz
    version: 16.0.10
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r43
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.17.1-debian-12-r7
        - name: postgresql
          image: docker.io/bitnami/postgresql:17.5.0-debian-12-r3
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 17.5.0
    created: "2025-05-23T10:26:52.721805+02:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: f05ee2ef5efa8b9afc6adb207cd8cc3568a78ad07c0f93444490841a1df53e4e
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-16.7.4.tgz
    version: 16.7.4
  valkey:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.33.0-debian-12-r0
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r43
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.70.0-debian-12-r2
        - name: valkey
          image: docker.io/bitnami/valkey:8.1.1-debian-12-r0
        - name: valkey-sentinel
          image: docker.io/bitnami/valkey-sentinel:8.1.1-debian-12-r0
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 8.1.1
    created: "2025-05-23T10:26:52.724993+02:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Valkey is an open source (BSD) high-performance key/value datastore
      that supports a variety workloads such as caching, message queues, and can act
      as a primary database.
    digest: 6bf0c49cc160a8ca9962dcb4cc945f034639705fd2a7144d7a938ebcbfa50451
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    keywords:
    - valkey
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: valkey
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/valkey
    urls:
    - charts/valkey-3.0.4.tgz
    version: 3.0.4
generated: "2025-05-23T10:26:52.696303+02:00"
